### ISSUE TITLE
Microphone issue on OnePlus 5T

### ISSUE THREAD

**Issue by zkzipoo** [PixelExperience/packages_apps_Settings#11]
The build number is QQ1B.200105.004
PixelExperience_dumpling-10.0-20200124-0200-OFFICIAL

And occasionally the microphone is not picking up any voice when making the call. But it will be back to normal when restarted.

Thanks

**Comment by Hlcpereira** [comment]
Report in the device tree repo, XDA thread or in our Telegram Chat or the Telegram Chat that the maintainer created for the device specific community. Any bug reports on the ROM source repos won't be considered.

Thanks for the comprehension and best regards.
