### ISSUE TITLE
Camera Button Issue

### ISSUE THREAD

**Issue by EggOxygen** [PixelExperience/packages_apps_Settings#12]
Seems these is a problem in here.
I have a pdx206 ( Xperia 5 Mark 2 ) Which have a camera key.
And in recent source i notice that button function comeback.
But it won't show in Settings. But now i can pass it by change the code

https://github.com/PixelExperience/packages_apps_Settings/blob/7823e2e47fa8ea3e390bf16f7bcbbd139254189b/src/com/android/settings/custom/buttons/ButtonSettingsPreferenceController.java#L30

with `return AVAILABLE;` which can solve my problem temporary. But it not a forever solution.

So please check the code at the link below, Oh perhaps i am missing some config. Please point it out. Thanks.

https://github.com/PixelExperience/packages_apps_Settings/blob/7823e2e47fa8ea3e390bf16f7bcbbd139254189b/src/com/android/settings/custom/buttons/ButtonSettingsUtils.java#L27

**Comment by jhenrique09** [comment]
Nice catch, i will push a patch to gerrit
